Enhancement/author
ITU-BDSA2024-GROUP14/Chirp pull request #122
Opened 2024-10-21 07:56 UTC by iiinaD

2024-10-21 08:14 UTC, esser2002 submitted a review, later dismissed

2024-10-21 08:14 UTC, esser2002 commented on src/Chirp.Razor/ChirpService.cs
> +public record CheepViewModel(string Author, string Message, string Timestamp);
Record 'CheepViewModel' is never used

2024-10-21 08:14 UTC, esser2002 commented on src/Chirp.Razor/ChirpService.cs
> +    }
Should this be handled in the service?
(I am actually not sure)

2024-10-21 08:14 UTC, esser2002 commented on src/Chirp.Razor/ChirpService.cs
> +        if (GetAuthor(authorName, authorEmail) == null)
Should this be != and not == ?

2024-10-21 08:17 UTC, JonathanVil requested changes

2024-10-21 08:17 UTC, JonathanVil commented on src/Chirp.Core/AuthorRepository.cs
> +    public Author? GetAuthor(string? authorName = null, string? authorEmail = null);
I believe this should be two signatures, as this poses the questions:
1. Can an author be retrieved by both name and email at the same time?
2. Can an author by retrieved without any parameters?

This signature allows for both of these.

2024-10-21 08:17 UTC, JonathanVil commented on src/Chirp.Core/AuthorRepository.cs
> +        return (list.Count == 0) ? null : list.First();
Use [`FirstOrDefault`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.firstordefault?view=net-8.0) to achieve same functionality, but avoid loading potentially multiple results

2024-10-21 09:59 UTC, JonathanVil requested changes

2024-10-21 09:59 UTC, JonathanVil commented on src/Chirp.Core/AuthorRepository.cs
> +        return GetAuthor(authorEmail: authorEmail);
Maybe call FirstOrDefault directly on the Authors DbSet here?

2024-10-21 09:59 UTC, JonathanVil commented on src/Chirp.Core/AuthorRepository.cs
> +        return GetAuthor(authorName);
Maybe call FirstOrDefault directly on the Authors DbSet here?

2024-10-22 10:19 UTC, JonathanVil approved these changes

2024-10-22 10:20 UTC, merged