Report/license
ITU-BDSA2024-GROUP14/Chirp pull request #243
Opened 2024-12-03 12:16 UTC by AugustBugge

2024-12-03 12:47 UTC, Oliverst8 requested changes

2024-12-03 12:47 UTC, Oliverst8 commented on docs/report.md
Please add a beginning to the section, since it starts very sudden

2024-12-03 12:47 UTC, Oliverst8 commented on docs/report.md
> +Therefore the choice of license was open, and the MIT license was used.
Therefore the choice of license was open -> Therefore the choice of license was _left_ open

Maybe?

2024-12-03 12:47 UTC, Oliverst8 commented on docs/report.md
> +It also means the program can be used as is, and the developers have no responsibility for maintaining the product.
Maybe add something about we we want this

2024-12-03 12:47 UTC, Oliverst8 commented on docs/report.md
> +Therefore the choice of license was open, and the MIT license was used.
And the MIT license was chosen

2024-12-03 12:47 UTC, Oliverst8 commented on docs/report.md
> +The MIT license is one of the most permissive licenses, allowing the program to be used for almost anything as long as the original copyright notice and license is included.
"license _is_ included" -> "license _are_ included"

2024-12-03 12:47 UTC, Oliverst8 commented on docs/report.md
> +It also means the program can be used as is, and the developers have no responsibility for maintaining the product.
Maybe change the beginning _It_ to _this_

2024-12-16 11:09 UTC, JonathanVil approved these changes
Looks good

2024-12-16 11:10 UTC, Oliverst8 approved these changes

2024-12-16 11:10 UTC, merged